sudo: required

language: ruby

services:
  - docker

cache:
  directories:
  - thesis/texmf

before_install:
  - docker build -t guusk/docker-latex-thesis .
  - tar xfz thesis-src.tgz
  - patch thesis/Makefile Makefile.patch

script:
  - docker run -it -v $(pwd)/thesis:/data guusk/docker-latex-thesis bash -c "test -f texmf/ls-R && make all || make fonts acrotex" 
